# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/clake/userextended/models/Settings/columns.yaml

# Model Class name
modelClass: Clake\Userextended\Models\Settings

# List Title
title: Settings